name:                valeo
version:             0.1.1
github:              "Alias Qli/valeo"
license:             BSD3
author:              "Alias Qli"
maintainer:          "2576814881@qq.com"
copyright:           "2021 Alias Qli"

synopsis:            A simple validator for web applications.
category:            Web

description:         Please see the README on GitHub at <https://github.com/Alias Qli/valeo#readme>

dependencies:
- base >= 4.7 && < 5
- text
- template-haskell
- th-abstraction
- semiring-simple
- email-validate

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  valeo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - valeo
